[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_program = "3Sw2qZje3Cxh4dsNwURMsJ8Jqby82JxtTiiPo3o5EX89"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/arlen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
